#!/bin/bash
#step1 Synthetic data generation
mkdir data
for k in 0.1 0.2 0.3;do
    mkdir data/noise_${k}
    for i in 75 100;do
        for j in 10000 15000;do
            python synthetic_bicluster.py --output_data ./data/noise_${k}/${j}_${i} --output_clusters ./data/noise_${k}/${j}_${i}_put --cols ${i} --rows ${j} --clustcols 20 --clustrows 500 --clusts 3 --noise $k
        done
    done
done

#Step2 Clustering the generated dataset with Noibic
mkdir time_mem_out
for k in 0.1 0.2 0.3;do
    for i in 75 100;do
        for j in 10000 15000;do
            nohup /usr/bin/time -v ../noibic -i ./data/noise_${k}/${j}_${i} -q 0.5 -o 3 > ./time_mem_out/out_noise_${k}_${j}_${i} 2>&1 &
        done
    done
done
wait

#Step3 Format conversion
mkdir found
for k in 0.1 0.2 0.3;do
    for i in 75 100;do
        for j in 10000 15000;do
            python convert_biclusters.py ./data/noise_${k}/${j}_${i}.blocks ./found/noise_${k}_${j}_${i}
        done
    done
done

#Step4 Metric computation
mkdir rel_rec
for k in 0.1 0.2 0.3;do
    for i in 75 100;do
        for j in 10000 15000;do
            python bicluster_metrics.py --expected ./data/noise_${k}/${j}_${i}_put --found ./found/noise_${k}_${j}_${i} --metric jaccard > ./rel_rec/noise_${k}_${j}_${i}
        done
    done
done
